/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function ping(): string
export interface OcrResult {
  text: string
  timestamp: string
  frameNumber: number
}
export declare function takeOneScreenshotAndDoOcr(): Promise<OcrResult | null>
export declare function takeMultipleScreenshotsAndDoOcr(recordLengthInSeconds: number): Promise<Array<OcrResult>>
