/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function ping(): string
export interface OcrResult {
  text: string
  timestamp: string
  frameNumber: number
}
export declare function takeOneScreenshotAndDoOcr(): Promise<OcrResult | null>
export declare function takeMultipleScreenshotsAndDoOcr(recordLengthInSeconds: number): Promise<Array<OcrResult>>
export declare function recordScreenImages(fps: number, duration: number, outputDirScreenshot: string): Promise<void>
export declare function recordScreenVideo(
  fps: number,
  duration: number,
  videoChunkDurationInSeconds: number,
  outputDirVideo: string,
): Promise<void>
export interface FrameData {
  ocrText: string
  timestamp: string
}
export declare function processImage(imagePath: string): Promise<FrameData>
export declare function processVideo(videoPath: string): Promise<Array<FrameData>>
export declare function processImageVisionFromPath(
  imagePath: string,
  url: string,
  apiKey: string,
  model: string,
  prompt: string,
): Promise<string>
export declare function add(a: number, b: number): Promise<number>
